name: Deploy to Alwaysdata

on:
  push:
    branches:
      - main  # Déclenche le workflow à chaque push sur main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code depuis GitHub
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configurer SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ALWAYSDATA_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ssh-sae-manager-g4.alwaysdata.net >> ~/.ssh/known_hosts

      # 3️⃣ Déployer sur Alwaysdata
      - name: Deploy
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no sae-man_
