name: Deploy to Alwaysdata

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SSH keys
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Connect and deploy
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd ~/www
          # Initialisation du dépôt si ce n'est pas déjà un git
          git init
          git remote add origin git@github.com:JeremyPanaiva/Sae_Manager_G4.git || true
          git fetch origin
          git reset --hard origin/main
          EOF

      - name: Cleanup
        run: rm -rf ~/.ssh
